# Generated by Django 4.0.4 on 2022-05-08 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 1, 18, 55, 754214, tzinfo=utc)),
        ),
    ]
