# Generated by Django 4.0.4 on 2022-05-10 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='No title provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 1, 12, 20, 874199, tzinfo=utc)),
        ),
    ]
